In [45]:
import pandas as pd
import numpy as np
import json
import sklearn
import sklearn.ensemble
from sklearn.ensemble import GradientBoostingClassifier

In [46]:
loans = pd.read_csv('../../uw_ml/data/lending-club-data.csv')

/Users/nehiljain/.pyenv/versions/3.4.6/envs/py34/lib/python3.4/site-packages/IPython/core/interactiveshell.py:2728: DtypeWarning: Columns (19,47) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


In [47]:
# safe_loans =  1 => safe
# safe_loans = -1 => risky
loans['safe_loans'] = loans['bad_loans'].apply(lambda x : +1 if x==0 else -1)
loans = loans.drop('bad_loans', axis = 1)

In [48]:
target = 'safe_loans'
features = ['grade',                     # grade of the loan (categorical)
            'sub_grade_num',             # sub-grade of the loan as a number from 0 to 1
            'short_emp',                 # one year or less of employment
            'emp_length_num',            # number of years of employment
            'home_ownership',            # home_ownership status: own, mortgage or rent
            'dti',                       # debt to income ratio
            'purpose',                   # the purpose of the loan
            'payment_inc_ratio',         # ratio of the monthly payment to income
            'delinq_2yrs',               # number of delinquincies
             'delinq_2yrs_zero',          # no delinquincies in last 2 years
            'inq_last_6mths',            # number of creditor inquiries in last 6 months
            'last_delinq_none',          # has borrower had a delinquincy
            'last_major_derog_none',     # has borrower had 90 day or worse rating
            'open_acc',                  # number of open credit accounts
            'pub_rec',                   # number of derogatory public records
            'pub_rec_zero',              # no derogatory public records
            'revol_util',                # percent of available credit being used
            'total_rec_late_fee',        # total late fees received to day
            'int_rate',                  # interest rate of the loan
            'total_rec_int',             # interest received to date
            'annual_inc',                # annual income of borrower
            'funded_amnt',               # amount committed to the loan
            'funded_amnt_inv',           # amount committed by investors for the loan
            'installment',               # monthly payment owed by the borrower
           ]

In [49]:
loans = loans[[target] + features].dropna()

In [50]:
loans = pd.get_dummies(loans)

In [51]:

with open('../../uw_ml/data/module-8-assignment-1-train-idx.json', 'r') as f: # Reads the list of most frequent words
    train_idx = json.load(f)
with open('../../uw_ml/data/module-8-assignment-1-validation-idx.json', 'r') as f1: # Reads the list of most frequent words
    validation_idx = json.load(f1)

In [52]:
train_data = loans.iloc[train_idx]
validation_data = loans.iloc[validation_idx]

In [53]:
validation_safe_loans = validation_data[validation_data[target] == 1]
validation_risky_loans = validation_data[validation_data[target] == -1]

sample_validation_data_risky = validation_risky_loans[0:2]
sample_validation_data_safe = validation_safe_loans[0:2]

sample_validation_data = sample_validation_data_safe.append(sample_validation_data_risky)
sample_validation_data

safe_loans  sub_grade_num  short_emp  emp_length_num    dti  \
22           1            0.2          0               3  29.44   
26           1            0.6          1               1  12.19   
24          -1            0.4          0               3  13.97   
41          -1            1.0          0              11  16.33   

    payment_inc_ratio  delinq_2yrs  delinq_2yrs_zero  inq_last_6mths  \
22            6.30496          0.0               1.0             0.0   
26           13.49520          0.0               1.0             0.0   
24            2.96736          3.0               0.0             0.0   
41            1.90524          0.0               1.0             0.0   

    last_delinq_none       ...         purpose_debt_consolidation  \
22                 1       ...                                  0   
26                 1       ...                                  0   
24                 0       ...                                  0   
41                 1       ...                                  1   

    purpose_home_improvement  purpose_house  purpose_major_purchase  \
22                         0              0                       0   
26                         0              0                       0   
24                         0              0                       0   
41                         0              0                       0   

    purpose_medical  purpose_moving  purpose_other  purpose_small_business  \
22                0               0              0                       0   
26                0               0              0                       0   
24                0               0              1                       0   
41                0               0              0                       0   

    purpose_vacation  purpose_wedding  
22                 0                0  
26                 0                0  
24                 0                0  
41                 0                0  

[4 rows x 45 columns]

In [54]:
sample_model = GradientBoostingClassifier(n_estimators=5, max_depth=6)

In [55]:
X = train_data.drop('safe_loans',1)

In [56]:
np.any(np.isnan(X))

False

In [57]:
sample_model.fit(X, train_data['safe_loans'])

GradientBoostingClassifier(criterion='friedman_mse', init=None,
              learning_rate=0.1, loss='deviance', max_depth=6,
              max_features=None, max_leaf_nodes=None,
              min_impurity_decrease=0.0, min_impurity_split=None,
              min_samples_leaf=1, min_samples_split=2,
              min_weight_fraction_leaf=0.0, n_estimators=5, presort='auto',
              random_state=None, subsample=1.0, verbose=0,
              warm_start=False)

In [58]:
sample_model.predict(sample_validation_data.drop('safe_loans',1))

array([ 1,  1, -1,  1])

In [59]:
sample_model.predict_proba(sample_validation_data.drop('safe_loans',1))

array([[0.41642331, 0.58357669],
       [0.46949689, 0.53050311],
       [0.53807792, 0.46192208],
       [0.39591639, 0.60408361]])

In [60]:
sample_model.score(validation_data.drop('safe_loans',1), validation_data['safe_loans'])

0.6614605773373546

In [61]:
predict_safeloans = sample_model.predict(validation_data.drop('safe_loans',1))

In [62]:
predict_safeloans

array([-1,  1, -1, ..., -1, -1, -1])

In [63]:
sum(predict_safeloans > validation_data['safe_loans'])

1652

In [64]:
# false negative
sum(predict_safeloans < validation_data['safe_loans'])

1491

In [65]:
validation_data['predictions'] = sample_model.predict_proba(validation_data.drop('safe_loans',1))[:,1]

/Users/nehiljain/.pyenv/versions/3.4.6/envs/py34/lib/python3.4/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.


In [67]:
validation_data[['grade_A','grade_B','grade_C','grade_D','predictions']].sort_values('predictions', ascending = False).head(5)

grade_A  grade_B  grade_C  grade_D  predictions
8021          1        0        0        0     0.673059
3489          1        0        0        0     0.661468
18304         1        0        0        0     0.661468
103476        1        0        0        0     0.661468
57584         1        0        0        0     0.661468